openapi: 3.0.3
info:
  title: User Service v1
  description: |-
    API for User Service
  termsOfService: http://swagger.io/terms/
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
paths:
components:
  schemas:
    ValidateUserCommand:
      type: object
      properties:
        reservationId:
          type: integer
        userId:
          type: integer
    UserValidatedEvent:
      type: object
      properties:
        reservationId:
          type: integer
        userId:
          type: integer
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        isClient:
          type: boolean