openapi: 3.0.3
info:
  title: Reservation Service v1
  description: |-
    API for Reservation Service
  termsOfService: http://swagger.io/terms/
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
tags:
  - name: Reservation
    description: A booking of a car
paths:
  /api/v1/reservation:
    post:
      tags:
        - Reservation
      description: Create a new Reservation
      operationId: createReservation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApiReservation'
      responses:
        '200':
          description: Successful operation
        '500':
          description: Internal Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'

  /api/v1/reservation-confirmation:
    post:
      tags:
        - Reservation
      description: Accept or Decline a previously requested reservation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApiReservationConfirmation'
      responses:
        '200':
          description: Successful operation
        '500':
          description: Internal Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'

  /api/v1/reservation-request:
    post:
      tags:
        - Reservation
      description: Create a new Reservation
      operationId: createReservationRequest
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApiReservationRequest'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiReservationRequestResponse'
        '500':
          description: Internal Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'

  /api/v1/reservations/{reservationId}/status:
    get:
      tags:
        - Reservation
      summary: Get the status of a specific reservation
      description: Retrieves the status of a reservation based on its unique identifier
      operationId: getReservationStatus
      parameters:
        - in: path
          name: reservationId
          required: true
          schema:
            type: integer
          description: Unique identifier of the reservation
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiReservationStatus'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        '404':
          description: Reservation Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        '500':
          description: Internal Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'

  /api/v1/reservations:
    get:
      tags:
        - Reservation
      summary: Get all reservations
      description: Retrieves a list of all reservations in the system
      operationId: getAllReservations
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiReservations'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        '500':
          description: Internal Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'

  /api/v1/reservation/search/{userId}:
    get:
      tags:
        - Reservation
      summary: Search for reservations by user's id
      description: Retrieves a list of reservations based on the id of the user
      operationId: searchReservationsByUserId
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: integer
          description: user id to search for reservations
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiReservations'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        '404':
          description: No Reservations Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        '500':
          description: Internal Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'

  /api/v1/reservation/price/{reservationId}:
    get:
      tags:
        - Reservation
      summary: Get price of reservation by reservationId
      description: Get price of reservation by reservationId
      operationId: getPriceByReservationId
      parameters:
        - in: path
          name: reservationId
          required: true
          schema:
            type: integer
          description: reservation id to get price of reservation
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiPrice'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        '404':
          description: No Reservations Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        '500':
          description: Internal Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'


components:
  schemas:
    ApiReservations:
      type: array
      items:
        $ref: '#/components/schemas/ApiReservation'
    ApiReservation:
      type: object
      properties:
        id:
          type: integer
        userId:
          type: integer
          example: 10
        neededCar:
          type: integer
          example: 11
        preferredStart:
          type: string
          format: date
          example: '2023-12-1'
        preferredEnd:
          type: string
          format: date
          example: '2023-12-4'

    ReservationCreatedEvent:
      type: object
      properties:
        id:
          type: integer
        userId:
          type: integer
        carId:
          type: integer
          example: 11
        preferredStart:
          type: string
          format: date
          example: '2023-12-1'
        preferredEnd:
          type: string
          format: date
          example: '2023-12-4'
        price:
          type: integer

    ApiError:
      type: object
      properties:
        code:
          type: string
          description: 'Functional code specifying the error'
          example: '2300'
        message:
          type: string
          description: 'Brief explanation about the error, for more information consult the Car Service team'

    ApiReservationRequest:
      type: object
      properties:
        userId:
          type: integer
        neededCar:
          type: integer
          example: 11
        preferredStart:
          type: string
          format: date
          example: '2023-12-1'
        preferredEnd:
          type: string
          format: date
          example: '2023-12-4'

    ApiPrice:
      type: object
      properties:
        price:
          type: integer

    ApiReservationStatus:
      type: object
      properties:
        status:
          type: string
          example: 'confirmed' # Possible values: confirmed, pending, cancelled, etc.

    ApiReservationRequestResponse:
      type: object
      properties:
        reservationRequestNumber:
          type: string
          example: "23-11-5678"

    ApiReservationConfirmation:
      type: object
      properties:
        reservationRequestNumber:
          type: string
          example: "23-11-5678"
        acceptProposedReservation:
          type: boolean

    ReservationCreationFailedEvent:
      type: object
      properties:
        reservationRequestNumber:
          type: string
          example: "23-11-5678"
        error:
          type: string